server {
    listen 8099 default_server;
    listen [::]:8099 default_server;

    root /app;
    index index.html;

    access_log off;
    error_log stderr;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
